/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Magic_rec;

import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author owner
 */
public class Home extends javax.swing.JFrame {
String path,p2;
String dest;
 int[] x1=new int[96];
 char[] a=new char[96];
 int[] x2=new int[96];     
int[] in2=new int[1000];
String s1;    
/**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        t1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        l1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Enhaced Data Security with Cryptograpghy & Steganography");

        jButton1.setText("Create magic Rectangle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter Message");

        t1.setColumns(20);
        t1.setRows(5);
        jScrollPane1.setViewportView(t1);

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", "", "", "", "", "", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jt1);
        jt1.getColumnModel().getColumn(0).setResizable(false);
        jt1.getColumnModel().getColumn(1).setResizable(false);
        jt1.getColumnModel().getColumn(2).setResizable(false);
        jt1.getColumnModel().getColumn(3).setResizable(false);
        jt1.getColumnModel().getColumn(4).setResizable(false);
        jt1.getColumnModel().getColumn(5).setResizable(false);
        jt1.getColumnModel().getColumn(6).setResizable(false);
        jt1.getColumnModel().getColumn(7).setResizable(false);
        jt1.getColumnModel().getColumn(8).setResizable(false);
        jt1.getColumnModel().getColumn(9).setResizable(false);
        jt1.getColumnModel().getColumn(10).setResizable(false);
        jt1.getColumnModel().getColumn(11).setResizable(false);

        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Browse Image:-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Data Hiding:-");

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton3.setText("Decrypt");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)
                                .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(l2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String clname[]={null,null,null,null,null,null,null,null,null,null,null,null};
        jScrollPane1.setViewportView(t1);

         
         jt1.setEnabled(false);
        String input=t1.getText();
        int[][] a=new int[4][6];
        int[][] b=new int [4][6];
    int[][] c=new int [4][6];
    int[][] d=new int [4][6];
        int rsum;
        int csum;
        int[] svalue={0,0,1,0};
        int mxst;
        int minst=4;
        csum=12345/4;
        rsum=(csum/2)+csum;
        mxst=(csum/2)-minst;
      a[0][0]=mxst;
a[0][1]=minst+2;
a[0][2]=minst+4;
a[0][3]=mxst-6;
a[0][4]=mxst-16;
a[0][5]=minst+16;
a[1][0]=minst+8;
a[1][1]=mxst-10;
a[1][2]=mxst-12;
a[1][3]=minst+14;
a[1][4]=minst+24;
a[1][5]=mxst-24;
a[2][0]=mxst-14;
a[2][1]=minst+12;
a[2][2]=minst+10;
a[2][3]=mxst-8;
a[2][4]=mxst-30;
a[2][5]=minst+30;
a[3][0]=minst+6;
a[3][1]=mxst-4;
a[3][2]=mxst-2;
a[3][3]=minst;
a[3][4]=minst+22;
a[3][5]=mxst-22;
minst=30+minst+2;
mxst=mxst-30-2;
b[0][0]=mxst;
b[0][1]=minst+2;
b[0][2]=minst+4;
b[0][3]=mxst-6;
b[0][4]=minst-14;
b[0][5]=mxst+14;
b[1][0]=minst+8;
b[1][1]=mxst-10;
b[1][2]=mxst-12;
b[1][3]=minst+14;
b[1][4]=mxst+6;
b[1][5]=minst-6;
b[2][0]=mxst-14;
b[2][1]=minst+12;
b[2][2]=minst+10;
b[2][3]=mxst-8;
b[2][4]=minst-4;
b[2][5]=mxst+4;
b[3][0]=minst+6;
b[3][1]=mxst-4;
b[3][2]=mxst-2;
b[3][3]=minst;
b[3][4]=mxst+12;
b[3][5]=minst-12;

minst=14+minst+2;
mxst=mxst-14-2;

 c[0][0]=mxst;
c[0][1]=minst+2;
c[0][2]=minst+4;
c[0][3]=mxst-6;
c[0][4]=mxst-16;
c[0][5]=minst+16;
c[1][0]=minst+8;
c[1][1]=mxst-10;
c[1][2]=mxst-12;
c[1][3]=minst+14;
c[1][4]=minst+24;
c[1][5]=mxst-24;
c[2][0]=mxst-14;
c[2][1]=minst+12;
c[2][2]=minst+10;
c[2][3]=mxst-8;
c[2][4]=mxst-30;
c[2][5]=minst+30;
c[3][0]=minst+6;
c[3][1]=mxst-4;
c[3][2]=mxst-2;
c[3][3]=minst;
c[3][4]=minst+22;
c[3][5]=mxst-22;
minst=30+minst+2;
mxst=mxst-30-2;
d[0][0]=mxst;
d[0][1]=minst+2;
d[0][2]=minst+4;
d[0][3]=mxst-6;
d[0][4]=minst-14;
d[0][5]=mxst+14;
d[1][0]=minst+8;
d[1][1]=mxst-10;
d[1][2]=mxst-12;
d[1][3]=minst+14;
d[1][4]=mxst+6;
d[1][5]=minst-6;
d[2][0]=mxst-14;
d[2][1]=minst+12;
d[2][2]=minst+10;
d[2][3]=mxst-8;
d[2][4]=minst-4;
d[2][5]=mxst+4;
d[3][0]=minst+6;
d[3][1]=mxst-4;
d[3][2]=mxst-2;
d[3][3]=minst;
d[3][4]=mxst+12;
d[3][5]=minst-12;
int  l=6;   
int [][] mr1=new int[8][12];
int [][] mr2=new int[8][12];
int [][] mr3=new int[8][12];
int [][] mr4=new int[8][12];

        for(int i=0;i<4;i++)
        {
            l=6;
            
            for(int j=0;j<6;j++)
            { 
            // jt1.setValueAt(a[i][j], i, j);
             mr1[i][j]=a[i][j];
             //jt1.setValueAt(b[i][j], i+4,j);
               mr1[i+4][j]=b[i][j];
             //jt1.setValueAt(c[i][j],i,l);
               mr1[i][l]=c[i][j];
            // jt1.setValueAt(d[i][j],i+4,l);
          mr1[i+4][l]=d[i][j];     
              l++;
            }
            
        } 
        int x=0;
         for(int i=0;i<8;i++)
        {
            for(int j=0;j<12;j++)
            {
                jt1.setValueAt(mr1[i][j], i, j);
                x1[x]=mr1[i][j];
                System.out.println(x1[x]+" "+x);
                x++;
            }
        }
        
           
        for(int i=0;i<96;i++)
        {
          System.out.println(x1[i]+" "+i);
           
        }
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        // TODO add your handling code here:\
        l1.setIcon(null);
        l2.setIcon(null);
          s1=t1.getText();
           JFileChooser file=new JFileChooser();
//        file.setCurrentDirectory(new File(System.getProperty("")));
FileNameExtensionFilter filter=new FileNameExtensionFilter("*.Images","jpg");
file.addChoosableFileFilter(filter);
int result=file.showSaveDialog(null);
File selectedFile;

if(result==JFileChooser.APPROVE_OPTION)
{
   selectedFile=file.getSelectedFile();
      path=selectedFile.getAbsolutePath();
      dest=selectedFile.getParent();
     System.out.println("n file selected -> "+path+"\n selectedFile.getParent();"+selectedFile.getParent()); 
      l1.setIcon(Resize(path));
      JOptionPane.showMessageDialog(new Home(),"Data Hiding start", "Information",JOptionPane.INFORMATION_MESSAGE);
    
      in2=new ImageDemo().ImageDemo1(path,s1,x1);
     
   l2.setIcon(Resize("MyFile3.png"));
    
}

else if(result==JFileChooser.CANCEL_OPTION)
{
    System.out.println("n file selected");
}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            int[] in3=in2;
                     a[0]=(char)0;
           int  j=1;
           System.out.println(s1);
        for(int i=32;i<127;i++)
        {
           
            a[j]=(char)i;//ascii value
         System.out.print(a[j]+" "+x1[j]+" ");
         
            j++;
            
        }
        
            System.out.println("hdfjghjdhgjhjgshj");
    

int i=0;
String s5="";
try{
    System.out.println("hdfjghjdhgjhjgshj");
while(in2[i]>0)
{
    j=0;
    while(j<96)
    {
        System.out.println(in2[i]);
        if(in2[i]==x1[j]){
             s5=s5+a[j]+"";
             s5=s1;
             System.out.println(a[j]);
        }
        j++;
    }
    i++;
        }
t4.setText(s5);
}
catch(Exception e){e.printStackTrace();}
    File f2=new File(path);//ssbtlogo
BufferedImage img2=ImageIO.read(f2);
        File f1=new File(p2);//myfile
BufferedImage img1=ImageIO.read(f1);
int len=img1.getWidth();
int len1=img1.getWidth()/2;
int first=0,sec;
int flag=0;
int[] in=new int[len1];
int k=0;
for(i=0;i<img1.getWidth();i++)
{
    
    for(j=0;j<img1.getHeight();j++)
    {
        if(i%2==0)
        {
            if(j==0){
                 
            first=Math.abs(Math.abs(img1.getRGB(i, j))-Math.abs(img2.getRGB(i,j)));
                     //System.out.println("fi->"+img1.getRGB(i, j)+" sec->"+img2.getRGB(i,j));
         //   System.out.println(first+"fi->"+img2.getRGB(i, j)+" sec->"+img1.getRGB(i, j));
            }
        }
        else
        {
            if(j==img1.getHeight()-1){ 
    
                 sec=Math.abs(Math.abs(img1.getRGB(i, j))-Math.abs(img2.getRGB(i,j)));
                     //ystem.out.println("fi->"+c1.getRGB()+" sec->"+img2.getRGB(i,j));
  //System.out.println(sec+"fi->"+img2.getRGB(i, j)+" sec->"+img1.getRGB(i, j));
       
            in[k]=first+sec+4;
            
    System.out.println("hi "+in[k]);
               k++;
               first=0;
               sec=0;
          
            }
           }
    }
}
i=0;
k=0;
String rs="";
while(k<len1)
{
    j=0;
    while(j<96)
    {
        if(x1[j]==in[k])
        {
            System.out.println(""+a[j]+" "+x1[j]);
            rs=rs+a[j]+"";
           //(rs);
        }
        j++;
    }
    k++;
}

        }
        catch(Exception e){}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jt1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextArea t1;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
private Icon Resize(String path) {
    ImageIcon MyImage=new ImageIcon(path);
    Image img=MyImage.getImage();
 //  int l= img.getHeight(b1);
   //System.out.println("l==="+l);
   //label.setSize(img.getWidth(b1),img.getHeight(b1));
    Image newImg=img.getScaledInstance(l1.getWidth(),l1.getHeight(),Image.SCALE_SMOOTH);
    ImageIcon image=new ImageIcon(newImg);
    return image;  
    }
}
